auction/auction/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

from notifications.views import (
    NotificationListView, MarkNotificationsView, EditNotificationSettings,
    EditMailSettings
)
from tenders.views import modal_content
from common.views import HomeView


admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', HomeView.as_view(), name='home'),
                       url(r'^modal-content/$', modal_content,
                           name='modal_content'),

                       url(r'^notifications/$', NotificationListView.as_view(),
                           name='notifications'),
                       url(r'^mark_notifications/$',
                           MarkNotificationsView.as_view(),
                           name='mark_notifications'),
                       url(r'^notification_settings/$',
                           EditNotificationSettings.as_view(),
                           name='notification_settings'),
                       url(r'mail_settings/$',
                           EditMailSettings.as_view(),
                           name='mail_settings'),
                       url(r'^employer/', include('employer.urls')),
                       url(r'^messages/', include('django_messages.urls')),
                       url(r'^accounts/', include('accounts.urls')),
                       url(r'^provider/', include('provider.urls')),
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),

                       url(r'^admin/', include(admin.site.urls)))

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)))

auction/tenders/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.urlresolvers import reverse_lazy
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from model_utils.models import TimeStampedModel

from accounts.models import User
from common.fields import CurrencyField
from common.mixin import GenericModelChoise


def limit_role_choices():
    return {
        'role__in': [User.Roles.PROVIDER_COMPANY,
                     User.Roles.PROVIDER_INDIVIDUAL]
    }


class Industry(GenericModelChoise):
    pass


@python_2_unicode_compatible
class Tenders(TimeStampedModel):
    class Types(object):
        OPEN = 0
        EMPLOYER = 1
        CLOSED = 2

        CHOICES = (
            (OPEN, _('Open view')),
            (EMPLOYER, _('Employer view')),
            (CLOSED, _('Closed view'))
        )

    class TypesPublic(object):
        PUBLIC = 1
        PRIVATE = 2

        CHOICES = (
            (PRIVATE, _('Private (a Private tender is only visible to Service Provides invited by the employer)')),
            (PUBLIC, _('Public (a Public tender is visible to everyone. Any Service Provider can view and bid)')),
        )

    user = models.ForeignKey(User, verbose_name=_('employer'),
                             related_name='user_tenders',
                             limit_choices_to={'role': User.Roles.EMPLOYER})
    title = models.CharField(_('title'), max_length=255)
    deadline = models.DateTimeField(_('deadline'))
    type = models.IntegerField(_('type of tender'), choices=Types.CHOICES,
                               default=Types.OPEN)
    type_public = models.IntegerField(('public type'),
                                      choices=TypesPublic.CHOICES,
                                      default=TypesPublic.PUBLIC)
    industry = models.ForeignKey(Industry, verbose_name=_('industry'),
                                 related_name='industry_tenders',
                                 limit_choices_to={'is_active': True})
    description = models.TextField(_('project description'))
    count_bids = models.PositiveIntegerField(_('count bids'), default=0)
    is_active = models.BooleanField(_('active'), default=True)
    is_withdraw = models.BooleanField(default=False)

    objects = models.Manager()

    def get_absolute_url(self):
        return reverse_lazy('employer-tender-detail', kwargs={'pk': self.pk})

    @property
    def is_expired(self):
        return now() > self.deadline

    class Meta:
        verbose_name = _('Tender')
        verbose_name_plural = _('Tenders')

    def __str__(self):
        return self.title


class BidsManager(models.Manager):
    def is_able_bid(self, user, tender_id):
        return self.filter(user=user, tender_id=tender_id).exists()


class Bids(TimeStampedModel):
    user = models.ForeignKey(User, verbose_name=_('provider'),
                             related_name='user_bids',
                             limit_choices_to=limit_role_choices())
    tender = models.ForeignKey(Tenders, verbose_name=_('tender'),
                               related_name='tender_bids')
    price = CurrencyField(_('best price'))

    objects = BidsManager()

    class Meta:
        verbose_name = _('Bid')
        verbose_name_plural = _('Bids')
        unique_together = ('user', 'tender')


@python_2_unicode_compatible
class TendersAttachments(models.Model):
    user = models.ForeignKey(User,
                             limit_choices_to={'role': User.Roles.EMPLOYER},
                             blank=True, null=True)
    tender = models.ForeignKey(Tenders, related_name='tendersattachments',
                               blank=True, null=True)
    tender_ident = models.CharField(_('tender_ident'), blank=True, null=True,
                                    max_length=255)
    file = models.FileField(upload_to='tenders/%Y/%m/%d')

    def __str__(self):
        return self.file.name.split('/')[-1]


@python_2_unicode_compatible
class BidsAttachments(models.Model):
    user = models.ForeignKey(User)
    tender = models.ForeignKey(Bids, related_name='bidsattachments',
                               blank=True, null=True)
    file = models.FileField(upload_to='bids/%Y/%m/%d')
    tender_ident = models.CharField(_('bids_ident'), blank=True, null=True,
                                    max_length=255)

    def __str__(self):
        return self.file.name.split('/')[-1]


@python_2_unicode_compatible
class InvitedProvider(models.Model):
    provider = models.ForeignKey(User, blank=True, null=True,
                                 related_name='invited_provider')
    user = models.ForeignKey(User, related_name='tender_own')
    tender = models.ForeignKey(Tenders)
    provider_email = models.EmailField(_('email address of provider'))

    def __str__(self):
        return self.provider_email


@receiver(post_save, sender=Bids, dispatch_uid='post_bids')
def post_bids(sender, instance=None, created=False, **kwargs):
    tender = instance.tender
    tender.count_bids = Bids.objects.filter(tender=tender).count()
    tender.save(update_fields=['count_bids'])

auction/tenders/views.py
# encoding: utf-8
from __future__ import unicode_literals

import json
import time

from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now
from django.views.generic import (ListView, CreateView, UpdateView, DetailView,
                                  View, TemplateView, DeleteView)
from django.views.generic.detail import SingleObjectMixin

from notifications.signals import notify
from notifications.tasks import (send_emails, get_rendered_notification)
from common.view_mixin import (
    AuthenticatedMixinView, AuthenticatedEmployerMixinView,
    ObjectOwnerPermMixin,
    ActiveTabMixin, AttachmentDeleteMixin
)

from .models import Tenders, TendersAttachments, InvitedProvider
from tenders.forms import (TendersModelForm, TendersAttachmentForm,
                           InviteProviderForm,)
from .templatetags.invited_provider import (
    get_email_list, get_invited_providers, get_provider_list,
    get_invited_search)


class EmployerTendersListView(ActiveTabMixin, AuthenticatedEmployerMixinView,
                              ListView):
    template_name = 'employer/employer_tenders.html'
    model = Tenders
    context_object_name = 'obj'
    active_tab = 'my_tenders'

    def get_queryset(self):
        qs = super(EmployerTendersListView, self).get_queryset()
        return (qs.filter(
            is_active=True, user=self.request.user, is_withdraw=False,
            deadline__gt=now()).order_by('-created'))

    def get_context_data(self, **kwargs):
        context = super(EmployerTendersListView, self).get_context_data(**kwargs)
        context['experied'] = Tenders.objects.filter(
            is_active=True, user=self.request.user).filter(
            Q(is_withdraw=True) | Q(deadline__lt=now())
        ).order_by('-created')
        context['active_tenders_tab'] = 'experied' \
            if self.request.COOKIES.get('page_click') == 'exp' else 'active'
        return context


class EmployerTenderDetailView(AuthenticatedMixinView, DetailView):
    queryset = Tenders.objects.filter(is_active=True)
    context_object_name = 'obj'
    template_name = 'tender/detail_tender.html'

    def render_to_response(self, context, **response_kwargs):
        if self.object.type_public == 2 and self.request.user.role:
            ids_provider = InvitedProvider.objects.filter(
                tender=self.object).values_list('provider', flat=True)
            if self.request.user.pk not in ids_provider:
                return HttpResponseRedirect(reverse_lazy('home'))
        return super(EmployerTenderDetailView, self).render_to_response(
            context, **response_kwargs)


class EmployerTendersCreateView(ActiveTabMixin, AuthenticatedEmployerMixinView,
                                CreateView):
    form_class = TendersModelForm
    model = Tenders
    template_name = 'employer/create_tender.html'
    active_tab = 'create_new_tender'
    initial = {}

    def form_valid(self, form):
        form.instance.user = self.request.user
        self.object = form.save()
        tender_ident = self.request.POST.get('tender_ident', None)

        if tender_ident:
            lookup = {
                'tender_ident': self.request.user.username + tender_ident,
                'user': self.request.user
            }

            TendersAttachments.objects.filter(**lookup).\
                update(tender=self.object)
        return HttpResponseRedirect(
            reverse_lazy('invite_provider', kwargs={'pk': self.object.pk}))

    def get_context_data(self, **kwargs):
        ctx = super(EmployerTendersCreateView, self).get_context_data(**kwargs)
        tender_ident = (self.request.POST.get('tender_ident') or
                        self.initial.get('tender_ident'))
        attach_list = []

        if tender_ident:
            lookup = {
                'tender_ident': self.request.user.username + str(tender_ident),
                'user': self.request.user
            }
            attach_list = TendersAttachments.objects.filter(**lookup)

        ctx.update({
            'tender_ident': tender_ident,
            'attach_list': attach_list
        })
        return ctx

    def get_initial(self):
        self.initial.update({'tender_ident': int(time.time() * 100)})
        try:
            experied_tender_id = self.request.GET.get('reinvite')
            experied_tender = Tenders.objects.get(
                pk=experied_tender_id)
        except Tenders.DoesNotExist:
            pass
        else:
            self.initial.update({
                'title': experied_tender.title,
                'type': experied_tender.type,
                'type_public': experied_tender.type_public,
                'industry': experied_tender.industry,
                'description': experied_tender.description
            })
            session_id = (self.request.user.username +
                          str(self.initial['tender_ident']))
            TendersAttachments.objects.bulk_create(
                TendersAttachments(
                    file=obj.file, tender_ident=session_id,
                    user_id=self.request.user.pk)
                for obj in TendersAttachments.objects.filter(
                    tender_id=experied_tender_id)
            )
        return self.initial.copy()


class TenderNotificationMixin(object):
    def send_notification(self, verb):
        user_ids = self.object.tender_bids.values_list('user', flat=True)

        if user_ids:
            notify.send(self.object.user, recipients=user_ids,
                        verb=verb, target=self.object)


class EmployerTendersEditView(AuthenticatedEmployerMixinView,
                              TenderNotificationMixin,
                              ObjectOwnerPermMixin,
                              UpdateView):
    form_class = TendersModelForm
    queryset = Tenders.objects.filter(is_active=True)
    template_name = 'employer/edit_tender.html'

    def form_valid(self, form):
        obj = super(EmployerTendersEditView, self).form_valid(form)
        self.send_notification('changed in tender')
        return obj

    def get_context_data(self, **kwargs):
        kwargs = super(EmployerTendersEditView, self).get_context_data(**kwargs)
        kwargs.update({'attach_list': TendersAttachments.objects.filter(
            tender=self.object, user=self.request.user)})
        return kwargs


class AttachmentsMixin(ObjectOwnerPermMixin,
                       SingleObjectMixin,
                       View):
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponse(_('Ok'))


class TendersAttachmentsDeleteView(AuthenticatedEmployerMixinView,
                                   AttachmentDeleteMixin):
    model = TendersAttachments


class TendersAttachmentsAddView(AuthenticatedEmployerMixinView,
                                CreateView):
    form_class = TendersAttachmentForm
    template_name = 'employer/includes/attach_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user

        kwargs = {'user': self.object.user}

        if not form.cleaned_data['tender']:
            session_id = (self.request.user.username +
                          form.cleaned_data['tender_ident'])
            self.object.tender_ident = session_id
            kwargs['tender_ident'] = self.object.tender_ident
        else:
            kwargs['tender'] = self.object.tender

        self.object.save()

        res = {
            'pk': self.object.pk,
            'file': self.object.file.name.encode('utf-8').split('/')[-1],
            'quan': TendersAttachments.objects.filter(**kwargs).count()
        }
        return HttpResponse(json.dumps(res), status=200)


class WithdrawView(AuthenticatedEmployerMixinView,
                   TenderNotificationMixin,
                   ObjectOwnerPermMixin,
                   UpdateView):
    http_method_names = ('post', )
    fields = []
    model = Tenders
    template_name = 'tender/withdrawview.html'

    def form_valid(self, form):
        if not form.instance.is_withdraw:
            form.instance.is_withdraw = True
            self.send_notification('withdrew tender')
        return super(WithdrawView, self).form_valid(form)


class InviteProviderView(AuthenticatedEmployerMixinView, TemplateView):
    template_name = 'tenders/invite_provider.html'

    def get_context_data(self, **kwargs):
        ctx = super(InviteProviderView, self).get_context_data(**kwargs)
        tender = get_object_or_404(Tenders, pk=self.kwargs['pk'])
        ctx.update({
            'tender': tender,
            'form': InviteProviderForm(),
        })
        return ctx


class InvitedProviderRenderMixin(object):

    def all_renders(self):
        search = self.request.POST.get('search', '')
        html_providers_list = render_to_string(
            'tenders/invited_providers_tags/provider_list.html',
            get_provider_list(self.tender)
        )
        html_email_list = render_to_string(
            'tenders/invited_providers_tags/email_list.html',
            get_email_list(self.tender)
        )
        html_invited_providers = render_to_string(
            'tenders/invited_providers_tags/invited_providers.html',
            get_invited_providers(self.tender)
        )
        html_invited_search = render_to_string(
            'tenders/invited_providers_tags/invited_providers.html',
            get_invited_search(self.tender.pk, search)
        )
        res = {'provider_list': html_providers_list,
               'email_list': html_email_list,

auction/templates/tenders/bids_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Withdraw bid' %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row-fluid kr-center-container ">
            <div class="kr-center kr-wrapper">
                <h3>{% trans "Withdraw bid" %}</h3>
            <hr />
            <form action="" method="post">{% csrf_token %}
                <div class="alert">

                {% trans 'Are you sure you want to delete your bid' %}?
                    </div>
                <div class="text-center">
                    <input class="btn-u" type="submit" value="Confirm"/>
                </div>
            </form>
                </div>
        </div>
    </div>
{% endblock %}

auction/templates/tenders/bids_edit.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Edit bid' %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row-fluid kr-center-container ">
            <div class="kr-center kr-wrapper">
                <form class="form-horizontal" method="post">
                    {% include 'tenders/bids_form_edit.html' %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

auction/templates/tenders/bids_form.html
{% load i18n %}
{% load getbids %}

{% csrf_token %}
{% for hidden in form.hidden_fields %}
    {{ hidden }}
{% endfor %}
<form class="form-horizontal" method="post" id="post-form"
      enctype="multipart/form-data">
    <input type="hidden" id="tender_ident" name="tender_ident"
           {% if tender_ident %}value="{{ tender_ident }}"{% else %}
           value="{% get_tender_ident %}"{% endif %}>

    {% for el in form.visible_fields %}
        {% include 'form_object.html' with obj=el only %}
    {% endfor %}
</form>

<div id="kr_attach_list" class="form-horizontal">
    <div class="control-group" style="margin-bottom: 0;">
        <span class="control-label">Attacments:</span>

        {% with attach_list as attachs %}
            <div class="controls empty_list"
                 style="display:{{ attachs|yesno:"none,block" }};">
                <span class="value">None</span>
            </div>
            {% for attach in attachs %}
                <div class="controls attach_controls">
                    <span>{{ attach }}</span>
                    <a href="{% url 'attachment-delete' attach.pk %}" class="delete_attach"
                       data-id="{{ attach.pk }}">×</a>
                </div>
            {% endfor %}
            <div class="clear-attach" style="display:{{ attachs|yesno:"block,none" }};"></div>
            <div class="controls progress-wrap"></div>
        {% endwith %}

    </div>
</div>
<div id="kr_attach" class="form-horizontal"></div>
<div class="form-horizontal">
    <div class="control-group">
        <div class="controls">
            <span class="btn-u bid_submit" >{% trans 'Bid' %}</span>
        </div>
    </div>
</div>

auction/templates/tenders/bids_form_edit.html
{% load i18n %}
{% for hidden in form.hidden_fields %}
    {{ hidden }}
{% endfor %}

{% for el in form.visible_fields %}
    {% include 'form_object.html' with obj=el only %}
{% endfor %}

auction/templates/tenders/bids_list.html
{% load i18n %}
{% for bid in bids %}
    <div class="pricing hover-effect" id="actor_{{ bid.user }}">
        <div class="pricing-head">
            <a href="{% url 'provider_profile' bid.user.pk %}" class="bid-title">
                {{ bid.user.company_name }}
            </a>
            <div class="bid-price">
                <i>$</i>
                {{ bid.price }}
            </div>
        </div>
    <div class="kr-center-container">
    {% with attachments=bid.bidsattachments.all %}
        {% if attachments %}
            <div class="attach_toggle"><i class="icon-file"></i> Attachments</div>
            <div class="attach_source" style="display:none;">
            {% for file in bid.bidsattachments.all %}
                <div>
                    <a href="{{ file.file.url }}" target="_blank">{{ file }}</a>
                </div>
            {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    </div>
        {% if user == bid.user and not tender.is_withdraw and not tender.is_expired %}
            <div class="pricing-footer">
                <a class="btn-u btn_modal_edit_bid" href="{% url 'bid-edit' bid.pk %}" data-bid_id="{{ bid.pk }}">{% trans 'Edit' %}</a>
                <a class="btn-u btn_modal" href="#" data-bid_id="{{ bid.pk }}" data-data='{"bid_id": {{ bid.pk }} }' data-template="tenders/modal_withdraw_bid.html">{% trans 'Withdraw' %} </a>
            </div>
        {% endif %}
    </div>
{% endfor %}

auction/templates/tenders/invite_provider.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load invited_provider %}

{% block extra-css %}
    <link rel="stylesheet"
          href="{% static 'css/jquery.mCustomScrollbar.css' %}"/>
{% endblock %}

{% block title %}{% trans 'Edit tender' %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row-fluid kr-wrapper">

                <h3>{% trans 'Invite Service providers to this Tender' %}</h3>
        <div class="row-fluid">
             <div class="span6">
                 <div class="text-center" style="margin-bottom:10px;">
                     <h4 style="margin-bottom:0;">Enter New Email addresses</h4>
                     (unregistered members would be sent an invite)
                 </div>
                 <div id="email_list">
                    {% get_email_list tender.pk %}
                 </div>
                 <div class="text-center"><h4>Enter email address</h4></div>
                    <form class="kr-form" method="post"
                          id="invite-form" action="">
                        <div style="display: inline-block;">
                            <div class="input-prepend">
                                {{ form.provider_email }}
                                <span class="add-on invite-submit">Invite</span>
                            </div>
                            <div class="help-block">{{ form.provider_email.errors.0 }}</div>
                        </div>
                    </form>
                <div class="kr-wrapper" style="margin-bottom:20px;">
                    <div class="text-center"><h4>Service providers already Invited to this tender</h4></div>
                    <div id="provider_list">
                        {% get_provider_list tender.pk %}
                    </div>
                </div>

            </div>
            <div class="span6">
                <div class="kr-wrapper" style="margin-bottom:20px;">
                    <div class="text-center"><h4>Frequently Invited Service Providers by you</h4></div>
                    <div id="invited_providers">
                        {% get_invited_providers tender %}
                    </div>
                </div>
                <div class="kr-wrapper" style="margin-bottom:20px;">
                    <form class="kr-form" method="post"
                          id="invite-search-form" action="">
                        <h4>Search for service provider</h4>
                        <div class="input-prepend" style="margin-bottom: 11px;">
                            <input type="text" id="invite-search-input"
                                   placeholder="Enter email or name" value=""
                                   autocomplete="off"/>
                            <span class="add-on invite-search-submit">Search
                        </span>
                        </div>
                    </form>
                    <div id="invited_search"></div>
                </div>
            </div>
        </div>
        <a class="btn-u" href="{% url 'employer-tender-detail' tender.pk %}" style="display:block; margin:0 auto 15px; width:28px;">Next</a>

        </div>
    </div>
{% endblock %}

{% block extra-js %}
    <script type="text/javascript"
        src="{% static 'js/jquery.mCustomScrollbar.concat.min.js'%}"></script>
    {% include 'employer/includes/tender_cu_extra_js.html' %}
    <script>
        {% include 'chunks/csrf_js.html' %}
        $('body').on('click', '.invite-submit', function(){
            tender = {{ tender.pk }};
            email = $('#id_provider_email').val();
            invite_add(tender, email)
        });

        $('.invite-search-submit').on('click', function(){
            $.post("{% url 'invite_search' %}", {
                'tender':{{ tender.pk }},
                'search': $('#invite-search-input').val()
            }, function(data){
                $('#invited_search .mCSB_container').html(data.invited_search).mCustomScrollbar("update");
            },'json')
        });

        $(window).load(function () {
            $("#email_list").mCustomScrollbar({
                autoHideScrollbar: true,
                theme: "rounded-dark"
            });
            $("#provider_list").mCustomScrollbar({
                autoHideScrollbar: true,
                theme: "rounded-dark"
            });
            $("#invited_providers").mCustomScrollbar({
                autoHideScrollbar: true,
                theme: "rounded-dark"
            });
            $("#invited_search").mCustomScrollbar({
                autoHideScrollbar: true,
                theme: "rounded-dark"
            });
        });

        function invite_add(tender, email){
            $.ajax({
                url: '{% url 'invite_add' %}',
                data: {
                    'tender': tender,
                    'provider_email': email,
                    'search': $('#invite-search-input').val()
                },
                type: 'POST',
                dataType: 'json',
                success: function(data){
                    if (data.valid){
                        blocks_render(data)
                    } else {
                        $('#invite-form').html(data.html)
                    }
                }
            });
        };
        function invite_delete(url){
            $.post(url, {
                'search': $('#invite-search-input').val()
            }, function(data){
                blocks_render(data);
            },'json')
        }

        function blocks_render(data){
            $('#id_provider_email').val('');
            par = $('#id_provider_email').parents('.input-prepend');
            par.next('.help-block').html('');
            $('#email_list .mCSB_container').html(data.email_list).mCustomScrollbar("update");
            $('#provider_list .mCSB_container').html(data.provider_list).mCustomScrollbar("update");
            $('#invited_providers .mCSB_container').html(data.invited_providers).mCustomScrollbar("update");
            $('#invited_search .mCSB_container').html(data.invited_search).mCustomScrollbar("update");
        }

    </script>
{% endblock %}

auction/templates/tenders/modal_edit_bid.html
{% extends 'tenders/modal_frame.html' %}
{% load i18n %}
{% block modal_title %} {% trans 'Edit bid' %}{% endblock %}

{% block modal_body %}
    <div class="row-fluid kr-center ">
        <form class="form-horizontal" method="post" id="form_edit_bid"
              enctype="multipart/form-data">
            {% include 'tenders/bids_form_edit.html' %}
        </form>
    </div>
    <div id="kr_attach_list" class="form-horizontal">
    <div class="control-group" style="margin-bottom: 0;">
        <span class="control-label">Attacments:</span>

        {% with attach_list as attachs %}
            <div class="controls empty_list"
                 style="display:{{ attachs|yesno:"none,block" }};">
                <span class="value">None</span>
            </div>
            {% for attach in attachs %}
                <div class="controls attach_controls">
                    <span>{{ attach }}</span>
                    <a href="{% url 'attachment-delete' attach.pk %}" class="delete_attach"
                       data-id="{{ attach.pk }}">×</a>
                </div>

            {% endfor %}
            <div class="clear-attach" style="display:{{ attachs|yesno:"block,none" }};"></div>
            <div class="controls progress-wrap"></div>
        {% endwith %}

    </div>
</div>
<div id="kr_attach" class="form-horizontal"></div>
{% endblock %}
{% block modal_footer %}
    <button type="button" class="btn btn-default"
            data-dismiss="modal">{% trans 'Close' %} </button>
    <a href="{% url 'bid-edit' bid_id %}"
       class="btn btn-u confirm-edit-bid" data-bid_id="{{ bid_id }}">{% trans 'Confirm' %}
    </a>
{% endblock %}

auction/templates/tenders/modal_frame.html
{% load i18n %}

<div class="modal-content">
    <div class="modal-header">
        <button type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"><span
                aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title"
            id="myModalLabel">
            {% block modal_title %}}{% endblock %}
        </h4>
    </div>
    <div class="modal-body kr-center-container">
            {% block modal_body %}{% endblock %}
    </div>
    <div class="modal-footer">
        {% block modal_footer %}{% endblock %}
    </div>
</div>

auction/templates/tenders/modal_withdraw_bid.html
{% extends 'tenders/modal_frame.html' %}
{% load i18n %}

{% block modal_title %} {% trans 'Withdraw bid' %}{% endblock %}

{% block modal_body %}{% trans 'Are you sure you want to delete your bid?' %}{% endblock %}
{% block modal_footer %}
    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %} </button>
    <a href="{% url 'bid-withdraw' context.bid_id %}"
       class="btn btn-u confirm-withdraw-bid" data-bid_id="{{ context.bid_id }}">{% trans 'Confirm' %}
    </a>
{% endblock %}

auction/templates/tenders/modal_withdraw_tender.html
{% extends 'tenders/modal_frame.html' %}
{% load i18n %}
{% block modal_title %} {% trans 'Withdraw Tender' %}{% endblock %}

{% block modal_body %}
    {% trans 'Are you sure that you want to withdraw tender?' %}
{% endblock %}

{% block modal_footer %}
    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
    <button type="button" class="btn btn-u confirm-withdraw-tender">{% trans 'Confirm' %}</button>
{% endblock %}