auction/auction/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

from notifications.views import (
    NotificationListView, MarkNotificationsView, EditNotificationSettings,
    EditMailSettings
)
from tenders.views import modal_content
from common.views import HomeView


admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', HomeView.as_view(), name='home'),
                       url(r'^modal-content/$', modal_content,
                           name='modal_content'),

                       url(r'^notifications/$', NotificationListView.as_view(),
                           name='notifications'),
                       url(r'^mark_notifications/$',
                           MarkNotificationsView.as_view(),
                           name='mark_notifications'),
                       url(r'^notification_settings/$',
                           EditNotificationSettings.as_view(),
                           name='notification_settings'),
                       url(r'mail_settings/$',
                           EditMailSettings.as_view(),
                           name='mail_settings'),
                       url(r'^employer/', include('employer.urls')),
                       url(r'^messages/', include('django_messages.urls')),
                       url(r'^accounts/', include('accounts.urls')),
                       url(r'^provider/', include('provider.urls')),
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),

                       url(r'^admin/', include(admin.site.urls)))

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)))

auction/employer/urls.py
# encoding: utf-8
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from employer.views import (
    EmployerProfileView, EmployerEditProfileView, EmployerSearchProvider
)
from tenders.views import (
    EmployerTendersListView, EmployerTenderDetailView, WithdrawView,
    EmployerTendersCreateView, EmployerTendersEditView,
    TendersAttachmentsDeleteView, TendersAttachmentsAddView, InviteProviderView,
    InviteAddView, InviteDeleteView, InviteSearchView)


urlpatterns = patterns('',
                       url(r'^tenders/$',
                           EmployerTendersListView.as_view(),
                           name='employer_tenders'),
                       url(r'^tender/(?P<pk>\d+)/$',
                           EmployerTenderDetailView.as_view(),
                           name='employer-tender-detail'),
                       url(r'^tender/create/$',
                           EmployerTendersCreateView.as_view(),
                           name='employer-tender-create'),
                       url(r'^tender/(?P<pk>\d+)/invite/$',
                           InviteProviderView.as_view(),
                           name='invite_provider'),
                       url(r'^tender/invite/search/$',
                           InviteSearchView.as_view(),
                           name='invite_search'),
                       url(r'^tender/(?P<pk>\d+)/edit/$',
                           EmployerTendersEditView.as_view(),
                           name='employer-tender-edit'),
                       url(r'^tender/(?P<pk>\d+)/withdraw/$',
                           WithdrawView.as_view(), name='withdraw-tender'),
                       url(r'^tender/attach/delete/(?P<pk>\d+)/$',
                           TendersAttachmentsDeleteView.as_view(),
                           name='tender_attachment'),
                       url(r'^tender/attach/add/$',
                           TendersAttachmentsAddView.as_view(),
                           name='tender_attachment_add'),
                       url(r'^tender/invite/delete/(?P<pk>\d+)/$',
                           InviteDeleteView.as_view(),
                           name='invite_delete'),
                       url(r'^tender/invite/add/$',
                           InviteAddView.as_view(),
                           name='invite_add'),
                       url(r'^profile/(?P<pk>\d+)/$',
                           EmployerProfileView.as_view(),
                           name='employer_profile'),
                       url(r'^change-profile/$',
                           EmployerEditProfileView.as_view(),
                           name='employer_change_profile'),
                       url(r'^search-providers/$',
                           EmployerSearchProvider.as_view(),
                           name='search_providers'),

)

auction/tenders/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.urlresolvers import reverse_lazy
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from model_utils.models import TimeStampedModel

from accounts.models import User
from common.fields import CurrencyField
from common.mixin import GenericModelChoise


def limit_role_choices():
    return {
        'role__in': [User.Roles.PROVIDER_COMPANY,
                     User.Roles.PROVIDER_INDIVIDUAL]
    }


class Industry(GenericModelChoise):
    pass


@python_2_unicode_compatible
class Tenders(TimeStampedModel):
    class Types(object):
        OPEN = 0
        EMPLOYER = 1
        CLOSED = 2

        CHOICES = (
            (OPEN, _('Open view')),
            (EMPLOYER, _('Employer view')),
            (CLOSED, _('Closed view'))
        )

    class TypesPublic(object):
        PUBLIC = 1
        PRIVATE = 2

        CHOICES = (
            (PRIVATE, _('Private (a Private tender is only visible to Service Provides invited by the employer)')),
            (PUBLIC, _('Public (a Public tender is visible to everyone. Any Service Provider can view and bid)')),
        )

    user = models.ForeignKey(User, verbose_name=_('employer'),
                             related_name='user_tenders',
                             limit_choices_to={'role': User.Roles.EMPLOYER})
    title = models.CharField(_('title'), max_length=255)
    deadline = models.DateTimeField(_('deadline'))
    type = models.IntegerField(_('type of tender'), choices=Types.CHOICES,
                               default=Types.OPEN)
    type_public = models.IntegerField(('public type'),
                                      choices=TypesPublic.CHOICES,
                                      default=TypesPublic.PUBLIC)
    industry = models.ForeignKey(Industry, verbose_name=_('industry'),
                                 related_name='industry_tenders',
                                 limit_choices_to={'is_active': True})
    description = models.TextField(_('project description'))
    count_bids = models.PositiveIntegerField(_('count bids'), default=0)
    is_active = models.BooleanField(_('active'), default=True)
    is_withdraw = models.BooleanField(default=False)

    objects = models.Manager()

    def get_absolute_url(self):
        return reverse_lazy('employer-tender-detail', kwargs={'pk': self.pk})

    @property
    def is_expired(self):
        return now() > self.deadline

    class Meta:
        verbose_name = _('Tender')
        verbose_name_plural = _('Tenders')

    def __str__(self):
        return self.title


class BidsManager(models.Manager):
    def is_able_bid(self, user, tender_id):
        return self.filter(user=user, tender_id=tender_id).exists()


class Bids(TimeStampedModel):
    user = models.ForeignKey(User, verbose_name=_('provider'),
                             related_name='user_bids',
                             limit_choices_to=limit_role_choices())
    tender = models.ForeignKey(Tenders, verbose_name=_('tender'),
                               related_name='tender_bids')
    price = CurrencyField(_('best price'))

    objects = BidsManager()

    class Meta:
        verbose_name = _('Bid')
        verbose_name_plural = _('Bids')
        unique_together = ('user', 'tender')


@python_2_unicode_compatible
class TendersAttachments(models.Model):
    user = models.ForeignKey(User,
                             limit_choices_to={'role': User.Roles.EMPLOYER},
                             blank=True, null=True)
    tender = models.ForeignKey(Tenders, related_name='tendersattachments',
                               blank=True, null=True)
    tender_ident = models.CharField(_('tender_ident'), blank=True, null=True,
                                    max_length=255)
    file = models.FileField(upload_to='tenders/%Y/%m/%d')

    def __str__(self):
        return self.file.name.split('/')[-1]


@python_2_unicode_compatible
class BidsAttachments(models.Model):
    user = models.ForeignKey(User)
    tender = models.ForeignKey(Bids, related_name='bidsattachments',
                               blank=True, null=True)
    file = models.FileField(upload_to='bids/%Y/%m/%d')
    tender_ident = models.CharField(_('bids_ident'), blank=True, null=True,
                                    max_length=255)

    def __str__(self):
        return self.file.name.split('/')[-1]


@python_2_unicode_compatible
class InvitedProvider(models.Model):
    provider = models.ForeignKey(User, blank=True, null=True,
                                 related_name='invited_provider')
    user = models.ForeignKey(User, related_name='tender_own')
    tender = models.ForeignKey(Tenders)
    provider_email = models.EmailField(_('email address of provider'))

    def __str__(self):
        return self.provider_email


@receiver(post_save, sender=Bids, dispatch_uid='post_bids')
def post_bids(sender, instance=None, created=False, **kwargs):
    tender = instance.tender
    tender.count_bids = Bids.objects.filter(tender=tender).count()
    tender.save(update_fields=['count_bids'])

auction/employer/forms.py
# encoding: utf-8
from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from accounts.models import User, Experience, Expertise, Employer
from common.forms import CompanyNameFormMixin


class SearchEmployerForm(forms.Form):
    type = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=User.Roles.CHOICES[1:],
        required=False)
    expertise = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=Expertise.objects.filter(is_active=True),
        required=False
    )
    experience = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=Experience.objects.filter(is_active=True),
        required=False
    )


class EmployerFormEdit(CompanyNameFormMixin, forms.ModelForm):
    company_name = forms.CharField(label=_('Company name'), required=True)

    class Meta:
        model = Employer
        fields = ['company_name', 'logo', 'description', 'facebook', 'twitter',
                  'google', 'linkedin', 'business_type', 'turnover',
                  'number_of_emloyees', ]

auction/tenders/forms.py
# encoding: utf-8
from __future__ import unicode_literals

from django.forms import ModelForm

from django import forms
from .models import Tenders, TendersAttachments, InvitedProvider
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from accounts.models import User
from django.conf import settings


class TendersModelForm(ModelForm):
    deadline = forms.SplitDateTimeField()
    edit_tender_id = forms.CharField(required=False,
                                     widget=forms.HiddenInput())
    tender_ident = forms.CharField(required=False,
                                     widget=forms.HiddenInput())

    class Meta:
        attachment_model = TendersAttachments
        model = Tenders
        fields = ('title', 'type_public', 'deadline', 'type', 'industry', 'description')

    def clean(self):
        super(TendersModelForm, self).clean()
        if 'deadline' in self.cleaned_data:
            if self.cleaned_data['deadline'] < timezone.now():
                self._errors["deadline"] = self.error_class(
                    ['Deadline should not be in the past'])
                del self.cleaned_data["deadline"]
        return self.cleaned_data


class TendersAttachmentForm(ModelForm):
    class Meta:
        model = TendersAttachments
        fields = ('file', 'tender_ident', 'tender')


class InviteProviderForm(forms.ModelForm):

    class Meta:
        model = InvitedProvider
        fields = ('provider_email',)

    def __init__(self, tender=None, *args, **kwargs):
        self.tender = tender
        super(InviteProviderForm, self).__init__(*args, **kwargs)

    def clean(self):
        super(InviteProviderForm, self).clean()
        if 'provider_email' in self.cleaned_data:
            if InvitedProvider.objects.filter(
                    provider_email=self.cleaned_data['provider_email'],
                    tender=self.tender):
                self.add_error('provider_email', _('Provider already invited'))
            else:
                try:
                    user = User.objects.get(email=self.cleaned_data['provider_email'])
                except User.DoesNotExist:
                    pass
                else:
                    if not user.role:
                        self.add_error('provider_email', _(
                            'He isn\'t provider'))
                    else:
                        self.instance.provider = user

auction/employer/views.py
# encoding: utf-8
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, UpdateView, View
from django.views.generic.base import TemplateResponseMixin
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse_lazy

from common.view_mixin import AuthenticatedEmployerMixinView, ActiveTabMixin,\
    AuthenticatedMixinView
from accounts.models import Employer
from employer.forms import SearchEmployerForm, EmployerFormEdit
from common.views import ChangeProfileMixinView


UserModel = get_user_model()


class EmployerProfileView(ActiveTabMixin, AuthenticatedMixinView,
                          DetailView):
    model = UserModel
    template_name = 'employer/employer_profile.html'
    active_tab = 'my_profile'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, pk=self.kwargs['pk'])


class EmployerEditProfileView(ChangeProfileMixinView,
                              AuthenticatedEmployerMixinView,
                              UpdateView):
    model = Employer
    form_class = EmployerFormEdit
    template_name = 'accounts/change_profile.html'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, user=self.request.user)

    def get_success_url(self):
        return reverse_lazy('employer_profile',
                            kwargs={'pk': self.request.user.pk})


class EmployerSearchProvider(ActiveTabMixin, TemplateResponseMixin, View):
    template_name = 'employer/employer_search.html'
    form_class = SearchEmployerForm
    active_tab = 'search_for_service_provider'

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.GET)
        lookup = {}
        ctx = {'form': form}
        if form.is_valid():
            roles = form.cleaned_data.get('type')
            default_roles = UserModel.Roles

            lookup['role__in'] = roles if roles else [
                default_roles.PROVIDER_INDIVIDUAL,
                default_roles.PROVIDER_COMPANY,
            ]

            qs = UserModel.objects.filter(**lookup)

            experience = form.cleaned_data.get('experience')
            if experience:
                qs = qs.filter(
                    Q(user_provider__year__in=experience) |
                    Q(user_provider_company__year__in=experience)
                )

            expertise = form.cleaned_data.get('expertise')
            if expertise:
                qs = qs.filter(
                    Q(user_provider__expertise__in=expertise) |
                    Q(user_provider_company__expertise__in=expertise)
                )

            ctx['object_list'] = qs.select_related().distinct()
            ctx['active_tab'] = self.get_active_tab()
        return self.render_to_response(ctx)

auction/templates/employer/includes/attach_form.html
<form class="form-horizontal" method="post"
      enctype="multipart/form-data" id="form_attach" action="{% url 'tender_attachment_add' %}">
<div style="visibility: hidden;position:absolute;">
    {{ form.file }}
</div>
<div class="control-group">
    <div class="controls">
        <span class="btn-u btn-attach" >Add more...</span>
    </div>
</div>
</form>

auction/templates/employer/includes/tender_attach_js.html
{% load staticfiles %}

<script type="text/javascript" src="{% static 'js/jquery.form.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        {% include 'chunks/csrf_js.html' %}
        $('body').on('click', '.btn-attach', function () {
            $('#id_file').trigger('click');
        });

        $('body').on('click', '.tender_submit', function () {
            $('#tender_form').submit();
        });

        $.get("{% url 'tender_attachment_add' %}", {}, function (data) {
            $('#kr_attach').html(data);
            {% if attach_list and attach_list|length >= 5  %}
                $('.btn-attach').hide();
            {% endif %}
        });

        $('body').on('change', '#id_file', function () {
            $('#form_attach').ajaxSubmit({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                    $('.empty_list').hide();
                    $('.progress-wrap').html('<div class="progress"><div class="bar"></div><div class="percent text-center">0%</div></div>');
                    var percentVal = '0%';
                    $('.bar').width(percentVal);
                    $('.percent').html(percentVal);
                },
                data: {
                    tender_ident: $('#id_tender_ident').val(),
                    tender: '{{ tender_id }}'
                },
                uploadProgress: function(event, position, total, percentComplete) {
                    var percentVal = percentComplete + '%';
                    $('.bar').width(percentVal);
                    $('.percent').html(percentVal);
                },
                dataType:  'json',
                complete: function(data) {
                    setTimeout(function(){
                        $('.progress').remove();
                        data = JSON.parse(data.responseText);
                        $('.clear-attach').show().before('<div class="controls attach_controls" ><span >' + data['file'] + '</span><a href="#file' + data['pk'] + '" class="delete_attach" data-id="' + data['pk'] + '">×</a></div>');
                        $('#id_file').val('');
                        if (data['quan'] >= 5) {
                            $('.btn-attach').hide()
                        }
                        if (data['quan'] != 0) {
                            $('.empty_list').hide();
                        }
                    } ,1000);
                }
            });
        });

        var url = '/employer/tender/attach/delete/';
        $('body').on('click', '.delete_attach', function (e) {
            var obj_id = $(this).data('id');
            var block = $(this).parent();
            $.post(url + obj_id + '/', function (data) {
                block.remove();
                if (data == 0) {
                    $('.empty_list').show();
                    $('.clear-attach').hide();
                }
                if (data <= 5) {
                    $('.btn-attach').show()
                }
            });
        });

    });
</script>

auction/templates/employer/includes/tender_cu_extra_js.html
{% load staticfiles %}

<script type="text/javascript"
        src="{% static 'js/moment-with-locales.js' %}"></script>
<script type="text/javascript"
        src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#id_deadline_1').parent().addClass('kr-date');
        $('#id_deadline_1').datetimepicker({
            useCurrent: true,
            format: 'hh:mm a',
            widgetPositioning: {
                horizontal: 'left',
                vertical: 'auto'
            },
            icons: {
                up: "glyphicon glyphicon-arrow-up",
                down: "glyphicon glyphicon-arrow-down"
            }
        }).attr('placeholder','Time');
        $('#id_deadline_0').datetimepicker({
            useCurrent: true,
            minDate: "{% now "m/d/Y" %}",
            format: 'DD/MM/YYYY',
            widgetPositioning: {
                horizontal: 'left',
                vertical: 'auto'
            },
            icons: {
                up: "glyphicon glyphicon-arrow-up",
                down: "glyphicon glyphicon-arrow-down"
            }
        }).attr('placeholder','Date');
    });
</script>

auction/templates/employer/includes/tender_form.html
{% load getbids %}

<form id="tender_form" class="form-horizontal" method="post"
      enctype="multipart/form-data">
    {% csrf_token %}
    {% for el in form.visible_fields %}
            {% include 'form_object.html' with obj=el only %}
    {% endfor %}
    <input type="hidden" id="id_edit_tender_id" name="edit_tender_id"
           value="{{ object.id }}">
    {{ form.tender_ident }}
    <input type="hidden" id="tender" name="tender" value="">
</form>
<div id="kr_attach_list" class="form-horizontal">
    <div class="control-group" style="margin-bottom: 0;">

        <span class="control-label">Attacments:</span>
        {% with attach_list as attachs %}
            <div class="controls empty_list"
                 style="display:{{ attachs|yesno:"none,block" }}; margin-bottom: 0;height: 22px; font-size:12px;">
                <span class="value" style="height:22px;">None</span>
            </div>
            {% for attach in attachs %}
                <div class="controls attach_controls">
                    <span>{{ attach }}</span>
                    <a href="#file{{ attach.pk }}" class="delete_attach"
                       data-id="{{ attach.pk }}">×</a>
                </div>

            {% endfor %}
        <div class="clear-attach" style="display:{{ attachs|yesno:"block,none" }};"></div>
        <div class="controls progress-wrap"></div>
        {% endwith %}
    </div>
</div>
<div id="kr_attach" class="form-horizontal"></div>
<div class="form-horizontal">
    <div class="control-group">
        <div class="controls">
            <span class="btn-u tender_submit">Submit</span>
        </div>
    </div>
</div>