auction/auction/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

from notifications.views import (
    NotificationListView, MarkNotificationsView, EditNotificationSettings,
    EditMailSettings
)
from tenders.views import modal_content
from common.views import HomeView


admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', HomeView.as_view(), name='home'),
                       url(r'^modal-content/$', modal_content,
                           name='modal_content'),

                       url(r'^notifications/$', NotificationListView.as_view(),
                           name='notifications'),
                       url(r'^mark_notifications/$',
                           MarkNotificationsView.as_view(),
                           name='mark_notifications'),
                       url(r'^notification_settings/$',
                           EditNotificationSettings.as_view(),
                           name='notification_settings'),
                       url(r'mail_settings/$',
                           EditMailSettings.as_view(),
                           name='mail_settings'),
                       url(r'^employer/', include('employer.urls')),
                       url(r'^messages/', include('django_messages.urls')),
                       url(r'^accounts/', include('accounts.urls')),
                       url(r'^provider/', include('provider.urls')),
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),

                       url(r'^admin/', include(admin.site.urls)))

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)))

auction/provider/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url, patterns

from .views import (
    MyBidsTendersView, MyProfileView, SearchTendersView, ChangeProviderView,
    ChangeProviderCompanyView, BidsCreateView, BidsEditView, BidDeleteView,
    AttachmentDeleteView, BidAttachmentsAddView
)


urlpatterns = patterns('',
                       url(r'^bids/$', MyBidsTendersView.as_view(),
                           name='provider_bids'),
                       url(r'^make_bid/$', BidsCreateView.as_view(),
                           name='make-bid'),
                       url(r'^bid/(?P<pk>\d+)/edit/$',
                           BidsEditView.as_view(), name='bid-edit'),
                       url(r'^bid/attachment_add/$',
                           BidAttachmentsAddView.as_view(), name='bid_attachment_add'),
                       url(r'^bid/(?P<pk>\d+)/attachment_delete/$',
                           AttachmentDeleteView.as_view(), name='attachment-delete'),
                       url(r'^bid/(?P<pk>\d+)/withdraw/$',
                           BidDeleteView.as_view(), name='bid-withdraw'),
                       url(r'^profile/(?P<pk>\d+)/$', MyProfileView.as_view(),
                           name='provider_profile'),
                       url(r'^search-tenders/$', SearchTendersView.as_view(),
                           name='search_tender'),
                       url(r'^change-profile/(?P<pk>\d+)/$',
                           ChangeProviderView.as_view(), name='change_profile'),
                       url(r'^change-profile/(?P<pk>\d+)/company/$',
                           ChangeProviderCompanyView.as_view(),
                           name='change_company_profile'),
)

auction/tenders/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.urlresolvers import reverse_lazy
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from model_utils.models import TimeStampedModel

from accounts.models import User
from common.fields import CurrencyField
from common.mixin import GenericModelChoise


def limit_role_choices():
    return {
        'role__in': [User.Roles.PROVIDER_COMPANY,
                     User.Roles.PROVIDER_INDIVIDUAL]
    }


class Industry(GenericModelChoise):
    pass


@python_2_unicode_compatible
class Tenders(TimeStampedModel):
    class Types(object):
        OPEN = 0
        EMPLOYER = 1
        CLOSED = 2

        CHOICES = (
            (OPEN, _('Open view')),
            (EMPLOYER, _('Employer view')),
            (CLOSED, _('Closed view'))
        )

    class TypesPublic(object):
        PUBLIC = 1
        PRIVATE = 2

        CHOICES = (
            (PRIVATE, _('Private (a Private tender is only visible to Service Provides invited by the employer)')),
            (PUBLIC, _('Public (a Public tender is visible to everyone. Any Service Provider can view and bid)')),
        )

    user = models.ForeignKey(User, verbose_name=_('employer'),
                             related_name='user_tenders',
                             limit_choices_to={'role': User.Roles.EMPLOYER})
    title = models.CharField(_('title'), max_length=255)
    deadline = models.DateTimeField(_('deadline'))
    type = models.IntegerField(_('type of tender'), choices=Types.CHOICES,
                               default=Types.OPEN)
    type_public = models.IntegerField(('public type'),
                                      choices=TypesPublic.CHOICES,
                                      default=TypesPublic.PUBLIC)
    industry = models.ForeignKey(Industry, verbose_name=_('industry'),
                                 related_name='industry_tenders',
                                 limit_choices_to={'is_active': True})
    description = models.TextField(_('project description'))
    count_bids = models.PositiveIntegerField(_('count bids'), default=0)
    is_active = models.BooleanField(_('active'), default=True)
    is_withdraw = models.BooleanField(default=False)

    objects = models.Manager()

    def get_absolute_url(self):
        return reverse_lazy('employer-tender-detail', kwargs={'pk': self.pk})

    @property
    def is_expired(self):
        return now() > self.deadline

    class Meta:
        verbose_name = _('Tender')
        verbose_name_plural = _('Tenders')

    def __str__(self):
        return self.title


class BidsManager(models.Manager):
    def is_able_bid(self, user, tender_id):
        return self.filter(user=user, tender_id=tender_id).exists()


class Bids(TimeStampedModel):
    user = models.ForeignKey(User, verbose_name=_('provider'),
                             related_name='user_bids',
                             limit_choices_to=limit_role_choices())
    tender = models.ForeignKey(Tenders, verbose_name=_('tender'),
                               related_name='tender_bids')
    price = CurrencyField(_('best price'))

    objects = BidsManager()

    class Meta:
        verbose_name = _('Bid')
        verbose_name_plural = _('Bids')
        unique_together = ('user', 'tender')


@python_2_unicode_compatible
class TendersAttachments(models.Model):
    user = models.ForeignKey(User,
                             limit_choices_to={'role': User.Roles.EMPLOYER},
                             blank=True, null=True)
    tender = models.ForeignKey(Tenders, related_name='tendersattachments',
                               blank=True, null=True)
    tender_ident = models.CharField(_('tender_ident'), blank=True, null=True,
                                    max_length=255)
    file = models.FileField(upload_to='tenders/%Y/%m/%d')

    def __str__(self):
        return self.file.name.split('/')[-1]


@python_2_unicode_compatible
class BidsAttachments(models.Model):
    user = models.ForeignKey(User)
    tender = models.ForeignKey(Bids, related_name='bidsattachments',
                               blank=True, null=True)
    file = models.FileField(upload_to='bids/%Y/%m/%d')
    tender_ident = models.CharField(_('bids_ident'), blank=True, null=True,
                                    max_length=255)

    def __str__(self):
        return self.file.name.split('/')[-1]


@python_2_unicode_compatible
class InvitedProvider(models.Model):
    provider = models.ForeignKey(User, blank=True, null=True,
                                 related_name='invited_provider')
    user = models.ForeignKey(User, related_name='tender_own')
    tender = models.ForeignKey(Tenders)
    provider_email = models.EmailField(_('email address of provider'))

    def __str__(self):
        return self.provider_email


@receiver(post_save, sender=Bids, dispatch_uid='post_bids')
def post_bids(sender, instance=None, created=False, **kwargs):
    tender = instance.tender
    tender.count_bids = Bids.objects.filter(tender=tender).count()
    tender.save(update_fields=['count_bids'])

auction/provider/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from accounts.models import ProviderIndividual, Expertise, ProviderCompany
from common.forms import CompanyNameFormMixin
from tenders.models import Industry, Bids, BidsAttachments


class SearchProviderForm(forms.Form):
    industry = forms.ModelChoiceField(
        queryset=Industry.objects.filter(is_active=True), required=False)
    #deadline = forms.DateTimeField(input_formats=['%m/%d/%Y %H:%M'], required=False)
    deadline = forms.DateField(required=False)
    is_open = forms.BooleanField(required=False)
    is_employer = forms.BooleanField(required=False)
    is_close = forms.BooleanField(required=False)


class ProviderAbstractForm(forms.ModelForm):
    expertise = forms.ModelMultipleChoiceField(
        queryset=Expertise.objects.filter(is_active=True),
        widget=forms.CheckboxSelectMultiple)

    class Meta:
        exclude = ('user', )


class ProviderIndividualForm(ProviderAbstractForm):
    class Meta(ProviderAbstractForm.Meta):
        model = ProviderIndividual


class ProviderIndividualFormEdit(CompanyNameFormMixin, ProviderAbstractForm):
    company_name = forms.CharField(label=_('Name'), required=True)

    class Meta(ProviderAbstractForm.Meta):
        model = ProviderIndividual
        fields = ['company_name', 'logo', 'description', 'facebook', 'twitter',
                  'google', 'linkedin', 'year', 'expertise', ]
        

class ProviderCompanyForm(ProviderAbstractForm):
    class Meta(ProviderAbstractForm.Meta):
        model = ProviderCompany


class ProviderCompanyFormEdit(CompanyNameFormMixin, ProviderAbstractForm):
    company_name = forms.CharField(label=_('Company name'), required=True)

    class Meta(ProviderAbstractForm.Meta):
        model = ProviderCompany
        fields = ['company_name', 'logo', 'description', 'facebook', 'twitter',
                  'google', 'linkedin', 'business_type', 'turnover',
                  'number_of_emloyees', 'year', 'expertise', ]


class BidsForm(forms.ModelForm):
    class Meta:
        model = Bids
        fields = ('price',)


class BidsAttachmentForm(forms.ModelForm):
    class Meta:
        model = BidsAttachments
        fields = ('file', 'tender_ident', 'tender')

auction/templates/provider/attach_form.html
<form class="form-horizontal" method="post"
      enctype="multipart/form-data" id="form_attach" action="{% url 'bid_attachment_add' %}">
<div style="visibility: hidden;position:absolute;">
    {{ form.file }}
</div>
<div class="control-group">
    <div class="controls">
        <span class="btn-u btn-attach" >Add more...</span>
    </div>
</div>
</form>

auction/templates/provider/bid_done.html
<div class="alert alert-info" style="margin-bottom:0;">You have already bid</div>

auction/templates/provider/bids.html
{% extends 'base.html' %}
{% load endless %}
{% load i18n %}

{% block title %}{% trans 'List of Active Tenders you have bid on' %}{% endblock %}

{% block content %}
<div class="container tender-list">
	<div class="row-fluid kr-wrapper">
        <div class="tabbable">
            <ul class="nav nav-tabs">
                <li {% if active_tenders_tab == 'active' %} class="active" {% endif %}><a href="#tab1" data-toggle="tab">Active
                    Tenders</a></li>
                <li {% if active_tenders_tab == 'experied' %} class="active" {% endif %}><a href="#tab2" data-toggle="tab">Expired Tenders</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane {% if active_tenders_tab == 'active' %}active{% endif %}" id="tab1">
                    <div class="row-fluid ">
                        <h3>{% trans 'List of Active Tenders you have bid on' %}</h3>
                        {% paginate 10 tender_list %}
                        <ul class="unstyled">
                            {% for tender in tender_list %}
                                <li>
                                    <a href="{% url 'employer-tender-detail' tender.id %}"
                                       class="tender-item hover-effect active">
                                        <span class="title">{{ tender.title }}</span>
                                        <span><strong>Type of Tender:</strong>
                                            {{ tender.get_type_display }}
                                        </span>
                                        <span><strong>Public Type:</strong>
                                            {{ tender.get_type_public_display }}
                                        </span>
                                        <span><strong>{% trans 'Posted' %}:</strong>
                                            {{ tender.created|date:"d/m/Y" }}
                                            {{ tender.created|time:"P" }}
                                        </span>
                                        <span><strong>{% trans 'Deadline' %}:</strong>
                                            {{ tender.deadline|date:"d/m/Y" }}
                                            {{ tender.deadline|time:"P" }}
                                        </span>
                                        <span><strong>{% trans 'Proposals' %}:</strong> {{ tender.count_bids }}</span>
                                    </a>
                                </li>
                            {% empty %}
                                {% trans "You don't have active bids." %}
                            {% endfor %}
                        </ul>
                    </div>

                        <div class="row-fluid pagination pagination-centered">
                            <span class="block">
                                {% show_pages %}
                            </span>
                        </div>
                </div>
                <div class="tab-pane {% if active_tenders_tab == 'experied' %}active{% endif %}" id="tab2">
                    <div class="row-fluid ">
                        <h3>{% trans 'List of Experied Tenders you have bid on' %}</h3>
                        {% paginate 10 experied using "experied_page" %}
                        <ul class="unstyled">
                            {% for tender in experied %}
                                <li>
                                    <a href="{% url 'employer-tender-detail' tender.id %}"
                                       class="tender-item hover-effect active">
                                        <span class="title">{{ tender.title }}</span>
                                        <span><strong>Type of Tender:</strong>
                                            {{ tender.get_type_display }}
                                        </span>
                                        <span><strong>Public Type:</strong>
                                            {{ tender.get_type_public_display }}
                                        </span>
                                        <span><strong>{% trans 'Posted' %}:</strong>
                                            {{ tender.created|date:"d/m/Y" }}
                                            {{ tender.created|time:"P" }}
                                        </span>
                                        <span><strong>{% trans 'Deadline' %}:</strong>
                                            {{ tender.deadline|date:"d/m/Y" }}
                                            {{ tender.deadline|time:"P" }}
                                        </span>
                                        <span><strong>{% trans 'Proposals' %}:</strong> {{ tender.count_bids }}</span>
                                    </a>
                                </li>
                            {% empty %}
                                {% trans "You don't have experied bids." %}
                            {% endfor %}
                        </ul>
                        <div class="row-fluid pagination pagination-centered">
                            <span class="block">{% show_pages %}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra-js %}
    {% include 'includes/multiple_paginator_js.html' %}
{% endblock %}

auction/templates/provider/search_tender.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load endless %}
{% load i18n %}

{% block menu_top %}
    {% with Active='search_tender' %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block extra-css %}
    <link rel="stylesheet"
          href="{% static 'css/bootstrap-datetimepicker.css' %}"/>
{% endblock %}

{% block title %}{% trans 'Search for tenders' %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row-fluid kr-wrapper">
            <h3>{% trans 'Search for tenders' %}</h3>

            <div class="span7">
                <h4>Filters</h4>

                <form class="form-horizontal" method="get" action=".">
                    <div class="control-group">
                        <label class="control-label" for="inputIndustry">
                            {% trans 'Industry' %}
                        </label>

                        <div class="controls">
                            {{ form.industry }}
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="inputDeadline">Deadline</label>

                        <div class='input-group date kr-date controls'
                             id='datetimepicker'>
                            <div class="input-append">
                                {{ form.deadline }}
                        <span class="input-group-addon add-on"><i
                                class="icon-calendar"></i>
                        </span>
                            </div>
                            {{ form.deadline.errors }}
                        </div>
                    </div>

                    <div class="control-group">
                        <span class="control-label">Type of Tender</span>

                        <div class="controls">
                            <label class="checkbox">
                                {{ form.is_open }}
                                {% trans 'Open View' %}
                            </label>
                            <label class="checkbox">
                                {{ form.is_employer }}
                                {% trans 'Employer View' %}
                            </label>
                            <label class="checkbox">
                                {{ form.is_close }}
                                {% trans 'Closed View' %}
                            </label>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn-u">Search</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="span4 tender-list" style="font-size: 0.86rem;">
                <h4>Search Results</h4>
                <ul class="unstyled row-fluid">
                    {% paginate 5 tender_list %}
                    {% for tender in tender_list %}
                        <li>
                            <div class="tender-item hover-effect
                                {% for u in tender.tender_bids.all %}
                                    {% if u.user == request.user %}
                                        bided
                                    {% endif %}
                                {% endfor %}">
                                <a href="{% url 'employer-tender-detail' tender.id %}" class="title">{{ tender.title }}</a>

                                <span class="tender-content">
                                    <span><strong>Type of Tender:</strong>
                                        {{ tender.get_type_display }}
                                    </span>
                                    <span><strong>Public Type:</strong>
                                        {{ tender.get_type_public_display }}
                                    </span>
                                    <span><strong>Posted:</strong>
                                        {{ tender.created|date:"d/m/Y" }}
                                        {{ tender.created|time:"P" }}

                                    </span>
                                    <span><strong>Deadline:</strong>
                                        {{ tender.deadline|date:"d/m/Y" }}
                                        {{ tender.deadline|time:"P" }}
                                    </span>

                                    <span><strong>Proposals:</strong> {{ tender.count_bids }}</span>
                                    <span><strong>Employer:</strong> <a href="{% url 'employer_profile' tender.user.pk %}">{{ tender.user.company_name}}</a></span>
                                 </span>
                            </div>
                        </li>
                        {% empty %}
                        We didn't find any tenders that match your search.
                    {% endfor %}
                </ul>
                <div class="row-fluid pagination pagination-centered">
                    <span class="block">
                        {% show_pages %}
                    </span>
                </div>
            </div>
        </div>
        <!--/row-fluid-->
    </div><!--/container-->
{% endblock %}

{% block extra-js %}
    <script type="text/javascript"
            src="{% static 'js/moment-with-locales.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker').datetimepicker({
                format: 'DD/MM/YYYY',
                widgetPositioning: {
                    horizontal: 'left',
                    vertical: 'auto'
                },
                icons: {
                    up: "glyphicon glyphicon-arrow-up",
                    down: "glyphicon glyphicon-arrow-down"
                }
            });
        });
    </script>
{% endblock %}